### ISSUE TITLE
[Bug]: Crash on Join 1.21.1 NeoForge

### ISSUE THREAD

**Issue by Zelioth** [TeamJM/journeymap#792]
### What happened?

Launched my client, joined our public server and appear to get this crash instantly on load. 

java.lang.NullPointerException: Cannot invoke "journeymap.api.v2.common.waypoint.WaypointGroup.isEnabled()" because the return value of "journeymap.common.waypoint.WaypointImpl.getGroup()" is null

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[crash-2024-09-13_13.42.40-client.txt](https://github.com/user-attachments/files/16998203/crash-2024-09-13_13.42.40-client.txt)
[latest.log](https://github.com/user-attachments/files/16998204/latest.log)

**Comment by mysticdrew** [comment]
Sorry for the delay on this crash. 
Are you able to send me your WaypointsData.dat file please?
located in your `minecraft/journeymap/data/{sp or mp}/{worldname}/waypoints` folder.
If you provided your journeymap.log file, I could tell you exactly where if you cannot find the file.

**Comment by Weyland** [comment]
Getting the same error but let me elaborate with some logs.

**Launcher error:**
```
Error: java.lang.NullPointerException: Cannot invoke "journeymap.api.v2.common.waypoint.WaypointGroup.isEnabled()" because the return value of "journeymap.common.waypoint.WaypointImpl.getGroup()" is null
```

**Stack trace:**
[message (2).txt](https://github.com/user-attachments/files/17169215/message.2.txt)

**Waypoints data:**
Working: [WaypointData.dat.txt](https://github.com/user-attachments/files/17169240/WaypointData.dat.txt)
Not working: Folder doesn't exist.

I'm going to try and fix it by sending my data to their profile install (ATM10, CurseForge) and check again.

**Comment by mysticdrew** [comment]
> Getting the same error but let me elaborate with some logs.
> 
> **Launcher error:**
> 
> ```
> Error: java.lang.NullPointerException: Cannot invoke "journeymap.api.v2.common.waypoint.WaypointGroup.isEnabled()" because the return value of "journeymap.common.waypoint.WaypointImpl.getGroup()" is null
> ```
> 
> **Stack trace:** [message (2).txt](https://github.com/user-attachments/files/17169215/message.2.txt)
> 
> **Waypoints data:** Working: [WaypointData.dat.txt](https://github.com/user-attachments/files/17169240/WaypointData.dat.txt) Not working: Folder exists, file doesn't exist.
> 
> I'm going to try and fix it by sending my data to their profile install (ATM10, CurseForge) and check again.



See
https://github.com/AllTheMods/ATM-10/issues/605#issuecomment-2380598308

**Comment by mysticdrew** [comment]
fixed in 1.21-6.0.0-beta.26 releasing shortly

**Comment by M-Kammler** [comment]
Just updated journeymap to beta.26 and i still get this error

**Comment by mysticdrew** [comment]
- 

> Just updated journeymap to beta.26 and i still get this error

provide logs

**Comment by M-Kammler** [comment]
https://pastebin.com/9xELaZ8j

**Comment by mysticdrew** [comment]
> Sry my bad, the former crash report may be on the old one, Here is one with the new journeymap version: https://pastebin.com/M4hdSknk

I tested this with minecolonies and it worked fine. 
Can you come into our discord so we can figure this out please?

**Comment by mysticdrew** [comment]
this thread
https://discord.com/channels/239040424214396929/1289667150247890954
